### PR TITLE
[HAC-76] As a user I can apply for invitation to Hacklag Slack

### PR DESCRIPTION
**Pull request by kkkowalski**
- Created backend code inside Syncano CodeBox ( validate email, send query to Slack & Discourse, retrieve answer, send JSON with response )
- Added new Syncano-JS library [Release 1.0.0]
- Added 2 new env vars: 
  - SYNCANO_API_KEY,
  - SYNCANO_INSTANCE_NAME
- Created 3 state component with reactions for:
  - reading user email,
  - successful invitation,
  - declined invitation

### CODE REVIEW

**Comment by mkucharz** [comment]
@kkkowalski only one comment, can you change "Slack" to "Registration" (routes, components)? It turned out that this way we are going just register user in different places so this is no only Slack anymore.

**Comment by kkkowalski** [comment]
@mkucharz Namespace changed to Registration, changed:
`/community/slack` to `/community/registration`
Names on Syncano Instance also changed by the same rule.

**Comment by mkucharz** [comment]
great, let's try it! ;)

**Comment by kkotelczuk** [comment]
lgtm

**Comment by StudentDawid** [comment]
lgtm

**Pull request merged**
