### PR TITLE
[HAC-270] Create separate page for full sponsors list 

### PR DESCRIPTION
**Pull request by kamilant**
*Added sponsors logo to sponsors page
*Created button on main page to sponsors page - "View all sponsors"
*Added styling to sponsors logo and some RWD
*Removed "to main page button" and added links in navigation - Home, Sponsors

### CODE REVIEW

**Comment by mkucharz** [comment]
@kamilant can you provide screenshot here in comments?

**Comment by kamilant** [comment]
@mkucharz 
screencapture-localhost-3000-sponsors-1475663729425

screencapture-localhost-3000-sponsors-1475664021237

**Comment by mkucharz** [comment]
@Idered @kamilant maybe instead "go to the main page" button we should have menu in the top pointing to that page?

**Comment by Idered** [comment]
Top nav links(on the left):
- Home
- Events
- Sponsors(?)

**Comment by kamilant** [comment]
@mkucharz @Idered Ok I'll add it, remove the "go to the main page button" and then I upload screenshots.

**Comment by kamilant** [comment]
@mkucharz 
screencapture-localhost-3000-sponsors-1475665222180

**Comment by kamilant** [comment]
@Idered @mkucharz Should "sponsors" link at /sponsors page redirect to sponsors section on home page? (/#sponsors)

**Comment by Idered** [comment]
@kamilant no, sponsors link should always redirect to /sponsors

**Review by kkotelczuk — APPROVED** [review]
LGTM

**Pull request merged**
